
  
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches:
    - main
    - release/*
  schedule:
  - cron: "16 9 * * MON-FRI"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install requests
    - name: Display Python version
      env:
        SCKEY: ${{ secrets.SERVERJIANG }}
      run: |
        echo ${{ secrets.SERVERJIANG }}
        python -c "import sys; print(sys.version)"
        python test.py
        date
